PORTNAME=	hachoir
DISTVERSION=	3.3.0
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ahze@FreeBSD.org
COMMENT=	Python library and tools to view and edit binary streams
WWW=		https://github.com/vstinner/hachoir

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python
USE_GITHUB=	yes
GH_ACCOUNT=	vstinner
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
